language: python

python:
  - 2.7
  - 3.1
  - 3.2
  - 3.3

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfftw3-dev cython
 - python cython_setup.py build_ext --inplace

install: pip install -r requirements.txt

script: python setup.py test
