language: python

python:
  - 2.7
  - 3.2

branches:
    except:
        - gh-pages

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfftw3-dev cython python-numpy python-scipy python3-numpy python3-scipy
 - cython pyfftw/pyfftw.pyx
 - cython pyfftw/utils.pxi

install: 
 - python setup.py build_ext --inplace

script: python setup.py test
