language: python

env:
    global:
        # github_changelog_generator API key
        - secure: "OX6AAzZeoC8SvhPbED0I59AhaSZr98kKoj8ZdLdkva6BVUJoR+giDCvARyzKT7Ikwoh8A1/Qo5BmEkWYXWxE8GRC+uyrKR67u0djv21oQB1y5NniWAxZ+WIr8beLvgJ3cbD6/pVrlkSz4VaDda09Ni6F/nOk00mj9N2fYq36DXCeK3mVIHXy1AhQxHbeDkISsfQsqBxSyz26fGbh/xbZwRFeD2EbHiRp/3STtae7VKbM02CNIS6zTpOzEfrd2oChRrteUZuCLz9yCRfi7awgJOJ00AsIdwuA8KktgNZWbOSHtrn7QaAuIyunBzZNleWkvcWIBHyE3eg9p49mv970W1QkKjh3CZI0uxVO6oeb934fbTXJSwVKh52rxFvKPh9qFZDCEj31tcrVThPEUT5DL6yx8EC+RhTPrWS37QcJoimMvSU9dKmiyNKnC0Lu3atRjq+qFv+ZLAEzAi4JV5L06VOpODHLijzb5zZ0FgysqpM+7jBzR92pf2kwupUwiDkGR7nzI49PnqZPnNTmYLol6i0LB80VPg3UKtBkJQXEIsbSRObwSlQ6oCp+FUI19O4dGcyY7uatu9JrsJtVjyDGuLd+A+HO/3SuugQV+F2QemU/mcQUnYrFpj4brF1FYSjaN9Sw8fTznzT1mYyD88Ii6arix2ApCSiTCrbtua9Tr1c="

os: linux

jobs:
  include:
    - python: 3.7
      env:
        - DASK_SPEC="dask=1.0"      # oldest supported
        - SCIPY_SPEC="scipy=1.2"     # oldest supported
        - NUMPY_SPEC="numpy=1.16"   # oldest supported
    - python: 3.8
      env:
        - DASK_SPEC="dask"  # most recent available
        - SCIPY_SPEC="scipy"
        - NUMPY_SPEC="numpy"
    - python: 3.9
      env:
        - DASK_SPEC="dask"  # most recent available
        - SCIPY_SPEC="scipy"
        - NUMPY_SPEC="numpy"

branches:
    except:
        - gh-pages

addons:
  apt:
    packages:
        libfftw3-dev

before_install:
  # reference: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html#the-travis-yml-file
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION setuptools cython $NUMPY_SPEC $SCIPY_SPEC $DASK_SPEC blas=*=openblas
  - conda activate test-environment
  - pip install -e . -v --no-build-isolation

script:
  - python setup.py test
  - travis/partial.sh

before_deploy:
  - rvm default
  - gem install github_changelog_generator
  - github_changelog_generator -u pyFFTW -p pyFFTW

deploy:
    provider: pypi
    skip_cleanup: true
    username: "pyfftw_citools"
    distributions: "sdist"
    password:
        secure: "n6/QGmA0PcMr9/ArpdS3jdcpMHlBOi6sXDT8jRV7MMaEaphsOkZAefK6/flJjwHA6oAu3lDDMJ1YsaxMfVMdSadUxpeYlh0f58WRryfcCIUFr9Rojz0iAtJNOZ1a+M6i6erwxif6y1f645sm72NAKX7m2KorGkH5CcjM+f4nABaLbAmAelIbYQpNMWOESEy2LKYx1xC7Gz1o3N4S/Z4g3o/to/1rNcQ0TujGHJBu/Skz+evhAkpPoEZjJI8TJChrhyODyVQwzNymiiBWmI0OxYmXi/HiH/NkmXjtXmbXVXKHJ7ReiyIAtJ1yDmDssPvnCYffP6Yrmpl9Zcp22LM0GmEIVXKfG5aj0csb784iZhweF1LySB/4mbModXxctO8otcZENnmQlpr3LJQX1hpUPQ9rg2J+uizbyg6loFdJ7V90XlRs4dMhtSIfTtP7zcaf2kYeq/JE56Hs9guMONewNxHtJNDRC4pG0j6VSsHMCdhFRkviLyTC/kbVFtY35uKQpT5e91L6yMRTWuMYUH2tEhmjgxnHOfP+MuXK3O/HttFBcd6gn66AUcO2KNQNHY2xbv35BUv1th64gqFTzrdjZ9j84MpfIk+z4v7bhCWP+sF2syzbYSkJN4WI/BVIi70Pmh7SvOy5dSQXEGNy96M5j4GxC8XVnHv7f82VS56UUqo="
    on:
        repo: pyFFTW/pyFFTW
        # We only need to build deploy one source release
        condition: $TRAVIS_PYTHON_VERSION = "3.6"
        tags: true
