environment:
    global:
        # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
        # /E:ON and /V:ON options are not enabled in the batch script intepreter
        # See: http://stackoverflow.com/a/13751649/163740
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
        # The miniconda installations are put in pyfftw_miniconda        
        PYTHON_HOME: "C:\\pyfftw_miniconda"

    pypi_username:
        secure: qFSpEDsIOj6gzynjuHTX5A==

    pypi_password:
        secure: zoj3LRJPmMpEKGa0nPGMsg==

    bintray_username:
        secure: mP8uIV/V4v9+zu0jCAU5mQ==

    bintray_api_key:
        secure: aBy9OwJetm6O29iWuEoWIsJc7Ml9NkiqTXDMClyHRePJcNdoTBZGOaMcHzm2ji77
  
    matrix:
  
        #    - PYTHON_VERSION: "2.7" # currently 2.7.9
        #      PYTHON_ARCH: "32"
        #            
        - PYTHON_VERSION: "2.7" # currently 2.7.9
          PYTHON_ARCH: "64"
    
        #    - PYTHON_VERSION: "3.3" # currently 3.3.5
        #      PYTHON_ARCH: "32"
        #
        #    - PYTHON_VERSION: "3.3" # currently 3.3.5
        #      PYTHON_ARCH: "64"
        #
        #    - PYTHON_VERSION: "3.4" # currently 3.4.3
        #      PYTHON_ARCH: "32"
        #      
        #    - PYTHON_VERSION: "3.4" # currently 3.4.3
        #      PYTHON_ARCH: "64"
        #
        #    - PYTHON_VERSION: "3.5"
        #      PYTHON_ARCH: "32"
        #      
        #    - PYTHON_VERSION: "3.5"
        #      PYTHON_ARCH: "64"

install:
    #- ECHO "Filesystem root:"
    #- ps: "ls \"C:/\""
  
    #- ECHO "Installed SDKs:"
    #- ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  
    # Get and configure the FFTW libs
    - "%CMD_IN_ENV% ./appveyor/setup_fftw_dlls.cmd"
  
    - ps: "./appveyor/install_miniconda.ps1"
  
    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;%PATH%"
  
    - "conda config --set always_yes yes"
    - "conda update -q conda"
    - "conda create -n build_env python=%PYTHON_VERSION% numpy scipy cython setuptools"
    - "activate build_env"
    - "%CMD_IN_ENV% python setup.py bdist_wheel"
    - "%CMD_IN_ENV% python setup.py build_ext --inplace"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Build the compiled extension and run the project tests
  - "python setup.py test"

deploy_script:
    - "echo [pypi] > %USERPROFILE%\\.pypirc"
    - "echo username: %pypi_username% >> %USERPROFILE%\\.pypirc"
    - "echo password: %pypi_password% >> %USERPROFILE%\\.pypirc"
    - ps: "./appveyor/deploy.ps1"

on_finish:
    # Uncomment the following to enable the remote environment
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#after_test:

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#
