environment:
    global:
        # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
        # /E:ON and /V:ON options are not enabled in the batch script intepreter
        # See: http://stackoverflow.com/a/13751649/163740
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
        # The miniconda installations are put in pyfftw_miniconda
        PYTHON_HOME: "C:\\pyfftw_miniconda"
        NP_BUILD_DEP: "=1.11"
        SP_BUILD_DEP: "=1.0"
        CYTHON_BUILD_DEP: "=0.29"
        DASK_BUILD_DEP: "=0.16"
        EXTRA_CONDA_ARGS: ""
        CONDA_ACTIVATE_CMD: "conda activate"

    pypi_username:
        secure: qFSpEDsIOj6gzynjuHTX5A==

    pypi_password:
        secure: zoj3LRJPmMpEKGa0nPGMsg==

    bintray_username:
        secure: mP8uIV/V4v9+zu0jCAU5mQ==

    bintray_api_key:
        secure: aBy9OwJetm6O29iWuEoWIsJc7Ml9NkiqTXDMClyHRePJcNdoTBZGOaMcHzm2ji77

    matrix:

        - PYTHON_HOME: "C:\\Miniconda"
          PYTHON_ARCH: "32"
          PYTHON_VERSION: "2.7"

        - PYTHON_HOME: "C:\\Miniconda-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: "2.7"

        - PYTHON_HOME: "C:\\Miniconda36"
          PYTHON_ARCH: "32"
          PYTHON_VERSION: "3.5"
          CONDA_ACTIVATE_CMD: "activate"

        - PYTHON_HOME: "C:\\Miniconda36-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: "3.5"
          CONDA_ACTIVATE_CMD: "activate"

        - PYTHON_HOME: "C:\\Miniconda36"
          PYTHON_ARCH: "32"
          PYTHON_VERSION: "3.6"

        - PYTHON_HOME: "C:\\Miniconda36-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: "3.6"

        - PYTHON_HOME: "C:\\Miniconda36"
          PYTHON_ARCH: "32"
          PYTHON_VERSION: "3.7"
          NP_BUILD_DEP: ""
          SP_BUILD_DEP: ""
          CYTHON_BUILD_DEP: ""
          DASK_BUILD_DEP: ""

        - PYTHON_HOME: "C:\\Miniconda36-x64"
          PYTHON_ARCH: "64"
          PYTHON_VERSION: "3.7"
          NP_BUILD_DEP: ""
          SP_BUILD_DEP: ""
          CYTHON_BUILD_DEP: ""
          DASK_BUILD_DEP: ""

install:
    # Get and configure the FFTW libs
    - "%CMD_IN_ENV% ./appveyor/setup_fftw_dlls.cmd"

    # activate the conda environment
    - CALL "%PYTHON_HOME%\\Scripts\\activate.bat"

    - "conda config --set always_yes yes --set changeps1 no"
    - "conda update -q conda"
    - "conda create -q -n build_env %EXTRA_CONDA_ARGS% python=%PYTHON_VERSION% numpy%NP_BUILD_DEP% scipy%SP_BUILD_DEP% cython%CYTHON_BUILD_DEP% dask%DASK_BUILD_DEP% setuptools"
    - "%CONDA_ACTIVATE_CMD% build_env"
    - "%CMD_IN_ENV% python setup.py -v bdist_wheel"
    - "%CMD_IN_ENV% python setup.py -v build_ext --inplace"

build: false  # Not a C# project, build stuff somewhere else.

test_script:
  # Run the project tests
  - "python setup.py test"

deploy_script:
    - "SET HOME=%USERPROFILE%"
    - "echo [server-login] > %USERPROFILE%\\.pypirc"
    - "echo username:%pypi_username% >> %USERPROFILE%\\.pypirc"
    - "echo password:%pypi_password% >> %USERPROFILE%\\.pypirc"
    - ps: "./appveyor/deploy.ps1"

on_finish:
    # Uncomment the following to enable the remote environment
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#after_test:

#on_success:
